{"name": "test_case_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 2) == 12", "trace": "def test_case_3():\n>       assert 1 +2 ==12\nE       assert (1 + 2) == 12\n\ntest_demo1.py:8: AssertionError"}, "attachments": [{"name": "log", "source": "dacbb826-cb54-4d27-bc27-372d6aa217bb-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "971d9e68-a990-4255-8c18-59d3436de0cf-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9be66e54-4f48-4107-81ec-3f44a27f46d8-attachment.txt", "type": "text/plain"}], "start": 1549234426938, "stop": 1549234426938, "uuid": "6d306a2f-c5e2-4135-8dd4-fde78b8d3813", "historyId": "368cd90a3c834aa79b6ac25f1e2404bd", "fullName": "test.pytest.test_demo1#test_case_3", "labels": [{"name": "parentSuite", "value": "test.pytest"}, {"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "Xiaobos-MacBook-Air.local"}, {"name": "thread", "value": "27959-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.pytest.test_demo1"}]}