{"name": "test_case_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 2) == 12", "trace": "def test_case_3():\n>       assert 1 +2 ==12\nE       assert (1 + 2) == 12\n\ntest_demo1.py:8: AssertionError"}, "attachments": [{"name": "log", "source": "dad01ed4-56c3-4783-8689-a98d3a8664ec-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "10340b1d-80a1-4b78-b704-3d3fba056157-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "cea4c502-8223-4ba0-bffa-522096f4eaa3-attachment.txt", "type": "text/plain"}], "start": 1549286677701, "stop": 1549286677702, "uuid": "e13718fb-a729-4f11-82b4-9386d0048ccd", "historyId": "9778af108f3ae600156b1c883c1dbb0e", "fullName": "test.test_demo1#test_case_3", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "Xiaobos-MacBook-Air.local"}, {"name": "thread", "value": "51653-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_demo1"}]}